# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1 # Limit the number of open PRs
    groups:
      dotnet: # Optional: Groups all .NET updates into a single PR
        patterns:
          - "*"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/dndgen-web/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1 # Limit the number of open PRs
    groups:
      angular: # Optional: Groups all Angular updates into a single PR
        patterns:
          - "*"
